[env]
    DB_USER=root
    DB_PASSWORD=xT54rNDN
    DB_HOST=localhost
    DB_PORT=3306
    DB_NAME=prisma
[services]
    [services.app]
        name = "your-app"
        image = "golang:latest"
        start_cmd = "go run main.go"
        build_dir = "./"
        port = 8080
